/**
 * /agent WebSocket protocol — gateway between the headless extension (agent)
 * and the Agent UI (console). Two client roles share one wire:
 *
 *   agent   = extension service worker. Reports live chat sessions, receives
 *             dispatch commands, answers with ack.
 *   console = Agent UI. Issues send commands, receives ack/failed/pending.
 *
 *   targetId     → chat session identity (company+title / HR identifier)
 *   connectionId → WS connection owning a session (generated by the gateway)
 */

export type AgentRole = 'agent' | 'console';

/** Extension service worker → gateway. */
export type AgentToGateway =
  | { type: 'hello'; role: 'agent'; agentId: string; sessionIds: string[] }
  | { type: 'session'; action: 'upsert' | 'remove'; targetId: string; tabId?: number }
  | { type: 'ping'; ts: number }
  | {
      type: 'ack';
      requestId: string;
      ok: boolean;
      /** Present when ok === false — e.g. the chat-box selector was not found. */
      error?: string;
      /** Small DOM context on success, so the console can show "what happened". */
      domSnippet?: string;
    };

/** Agent UI (console) → gateway. */
export type ConsoleToGateway =
  | { type: 'hello'; role: 'console' }
  | { type: 'send'; requestId: string; targetId: string; text: string };

/** Gateway → extension service worker. */
export type GatewayToAgent =
  | { type: 'dispatch'; requestId: string; targetId: string; text: string }
  | { type: 'pong'; ts: number };

/** Gateway → Agent UI (console). */
export type GatewayToConsole =
  | { type: 'hello'; ok: true; agents: number; sessions: SessionInfo[] }
  | { type: 'pending'; requestId: string; targetId: string }
  | {
      type: 'ack';
      requestId: string;
      ok: boolean;
      error?: string;
      domSnippet?: string;
    }
  | { type: 'failed'; requestId: string; reason: FailedReason };

export type FailedReason = 'tab-closed' | 'tab-idle' | 'selector-failed' | 'tab-offline';

export type SessionStatus = 'online' | 'offline';

/** Console-facing view of one chat session. */
export interface SessionInfo {
  targetId: string;
  tabId?: number;
  status: SessionStatus;
  lastSeen: number;
}
