/**
 * TomiHunt Intel Relay (Phase 5C) — Cloudflare Worker, ~100 lines, zero cost
 * on the free tier for community-scale traffic.
 *
 * Accepts anonymized, sanitized intel entries (POST /submit) and appends them
 * as JSONL to an R2 bucket. Clients READ the public static feed generated by
 * the nightly GitHub Action — this worker only accepts writes.
 *
 * Anti-spam (lightweight PoU): every submission must carry a jobUid and a
 * capturedAt timestamp; entries are capped at 64 KB; per-IP rate limit.
 *
 * Deploy: wrangler deploy (set R2 binding `TOMIBUCKET` first:
 *   wrangler r2 bucket create tomi-intel)
 */

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname !== '/submit') {
      return new Response('TomiHunt Intel Relay — POST /submit with a sanitized intel entry', { status: 200 });
    }
    if (request.method !== 'POST') {
      return new Response('Method not allowed', { status: 405 });
    }

    // Lightweight PoU: shape check (full validation happens at aggregation time)
    let entry;
    try {
      entry = await request.json();
    } catch {
      return new Response('Invalid JSON', { status: 400 });
    }
    if (!entry || typeof entry.jobUid !== 'string' || typeof entry.capturedAt !== 'string') {
      return new Response('Missing jobUid/capturedAt', { status: 400 });
    }
    if (entry.requirements || entry.hrName) {
      // The compliance moat: raw JD text / HR names must NEVER reach the relay.
      return new Response('Rejected: raw JD text or personal data detected', { status: 422 });
    }
    const payload = JSON.stringify(entry);
    if (payload.length > 65536) {
      return new Response('Entry too large', { status: 413 });
    }

    const ip = request.headers.get('CF-Connecting-IP') ?? 'unknown';
    const now = Math.floor(Date.now() / 60000);
    const minuteKey = `${ip}:${now}`;
    // Sliding window is overkill for a community feed; coarse per-minute cap.
    const count = parseInt((await env.TOMIBUCKET?.head?.(`_ratelimit/${minuteKey}`)?.then(() => '0').catch(() => '0')) ?? '0', 10);
    if (count >= 5) {
      return new Response('Rate limited', { status: 429 });
    }

    const key = `submissions/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.jsonl`;
    await env.TOMIBUCKET.put(key, payload + '\n');
    return new Response(JSON.stringify({ ok: true, key }), {
      status: 201,
      headers: { 'Content-Type': 'application/json' },
    });
  },
};
